// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Message struct {
	ID          int32
	PhoneNumber string
	Content     string
	ScheduledAt time.Time
	CreatedAt   sql.NullTime
	Status      sql.NullString
}
